- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Captain
  - CentralCommandOfficial
  - ChiefServiceSupervisor
  - ChiefEngineer
  - ChiefMedicalOfficer
  - ERTEngineer
  - ERTJanitor
  - ERTLeader
  - ERTMedical
  - ERTSecurity
  - HeadOfPersonnel
  - HeadOfSecurity
  - Mystagogue
  - ResearchDirector
  - SAI

- type: department
  id: Service
  description: department-Civilian-description
  color: "#9FED58"
  roles:
  - Bartender
  - Botanist
  - Boxer
  - Chef
  - Clown
  - Gladiator
  - ChiefServiceSupervisor
  - Janitor
  - Lawyer
  - Librarian
  - MartialArtist
  - MedicalIntern
  - Mime
  - Musician
  - Passenger
  - Reporter
  - ServiceWorker
  - Zookeeper


- type: department
  id: Cargo
  description: department-Engineering-cargo
  color: "#ba7233"
  roles:
  - SalvageTechnician
  - Quartermaster
  - MailCarrier

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  - MedicalRobot

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  roles:
  - HeadOfSecurity
  - PrisonGuard
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  - Prisoner

- type: department
  id: Epistemics
  description: department-Epistemics-description
  color: "#D381C9"
  roles:
  - Mystagogue
  - ForensicMantis
  - Epistemologist
  - Chaplain
  - Cataloguer
